spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competitiontraining?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    password: 123456
    username: root
  servlet:
    multipart:
      max-file-size: 50MB       #单个文件上传最大50MB
      max-request-size: 100MB   #并发上传大小限制为100MB
server:
  port: 453
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: 200573Cjj
    key-store-type: PKCS12
    key-alias: springboot